### ISSUE TITLE
Remove Buttons for Support and Template Combobox

### ISSUE THREAD

**Issue by brunocalado** [EddieDover/Theater-of-the-Mind#44]
**Describe the solution you'd like**
Hi. Can you add an option in settings to hide the support buttons?

Also, is possible to remove the template combobox from the dialog?
![image](https://github.com/EddieDover/Theater-of-the-Mind/assets/4999783/6dd0667b-ecb3-40bd-84ce-06651f273a0a)

**Describe alternatives you've considered**
Hide with CSS. It looks nice.

![image](https://github.com/EddieDover/Theater-of-the-Mind/assets/4999783/69dad96f-199d-436b-90d0-a0d79721501b)

Thank you.

**Comment by EddieDover** [comment]
I"ll see what sort of compromise I can come up with to minimize the amount of unused space.  I'm not sure completely removing the buttons is a good idea, since they provide ways users can get support, but I can definitely imagine ways we can fold them up when they're not needed. 

Also, maybe I can hide the combobox if there are not multiple files to choose from. Would that be acceptable?

**Comment by brunocalado** [comment]
> I"ll see what sort of compromise I can come up with to minimize the amount of unused space. I'm not sure completely removing the buttons is a good idea, since they provide ways users can get support, but I can definitely imagine ways we can fold them up when they're not needed.
> 
> Also, maybe I can hide the combobox if there are not multiple files to choose from. Would that be acceptable?

> Also, maybe I can hide the combobox if there are not multiple files to choose from. Would that be acceptable?
Good idea.

But, I would really prefer to check an option in settings to remove the support buttons and the combobox. Like I did with CSS.
