### ISSUE TITLE
SWADE Template not available

### ISSUE THREAD

**Issue by brunocalado** [EddieDover/Theater-of-the-Mind#62]
**Describe the bug**
If you open SWADE system the swade template is not available. You need to set it manually.
![image](https://github.com/EddieDover/Theater-of-the-Mind/assets/4999783/2f8f85e6-5a50-4c44-8fdf-17b23b20cd06)

**Comment by EddieDover** [comment]
By design no templates other than the built-in dnd5e template is loaded on a fresh install.

It is the onus of the user to copy a template they like from its relevant sub folder inside the example_templates directory, to their data/totm directory.

This is by design to:

1. Maintain expected compatibility for those who were originally using this plugin for dnd5e

2. Prevent unnecessarily loading potentially dozens of templates. 

3. Remain mostly system agnostic, as all templates besides dnd5e are *not* maintained by me, @EddieDover

**Comment by brunocalado** [comment]
Thank you.
